import { SpanishWord, QuizQuestion, FeedbackMessage } from './types';

export const SPANISH_WORDS: SpanishWord[] = [
  // --- Masculino ---
  {
    word: 'libro',
    article: 'el',
    translationRu: 'книга',
    translationHy: 'գիրք',
    isException: false,
    icon: 'BookOpen',
    gender: 'masculino',
  },
  {
    word: 'gato',
    article: 'el',
    translationRu: 'кот',
    translationHy: 'կատու',
    isException: false,
    icon: 'Cat',
    gender: 'masculino',
  },
  {
    word: 'perro',
    article: 'el',
    translationRu: 'собака',
    translationHy: 'շուն',
    isException: false,
    icon: 'Dog',
    gender: 'masculino',
  },
  {
    word: 'piano',
    article: 'el',
    translationRu: 'пианино',
    translationHy: 'դաշնամուր',
    isException: false,
    icon: 'Music',
    gender: 'masculino',
  },
  {
    word: 'micrófono',
    article: 'el',
    translationRu: 'микрофон',
    translationHy: 'միկրոֆոն',
    isException: false,
    icon: 'Mic',
    gender: 'masculino',
  },
  {
    word: 'teléfono',
    article: 'el',
    translationRu: 'телефон',
    translationHy: 'հեռախոս',
    isException: false,
    icon: 'Phone',
    gender: 'masculino',
  },
  {
    word: 'cuaderno',
    article: 'el',
    translationRu: 'тетрадь',
    translationHy: 'տետր',
    isException: false,
    icon: 'FileText',
    gender: 'masculino',
  },
  {
    word: 'bolígrafo',
    article: 'el',
    translationRu: 'ручка',
    translationHy: 'գրիչ',
    isException: false,
    icon: 'PenTool',
    gender: 'masculino',
  },
  // Exceptions Masculino
  {
    word: 'problema',
    article: 'el',
    translationRu: 'проблема',
    translationHy: 'խնդիր',
    isException: true,
    icon: 'HelpCircle',
    gender: 'masculino',
  },
  {
    word: 'mapa',
    article: 'el',
    translationRu: 'карта',
    translationHy: 'քարտեզ',
    isException: true,
    icon: 'Map',
    gender: 'masculino',
  },
  {
    word: 'día',
    article: 'el',
    translationRu: 'день',
    translationHy: 'օր',
    isException: true,
    icon: 'Sun',
    gender: 'masculino',
  },

  // --- Femenino ---
  {
    word: 'casa',
    article: 'la',
    translationRu: 'дом',
    translationHy: 'տուն',
    isException: false,
    icon: 'Home',
    gender: 'femenino',
  },
  {
    word: 'mesa',
    article: 'la',
    translationRu: 'стол',
    translationHy: 'սեղան',
    isException: false,
    icon: 'Table',
    gender: 'femenino',
  },
  {
    word: 'guitarra',
    article: 'la',
    translationRu: 'гитара',
    translationHy: 'կիթառ',
    isException: false,
    icon: 'Guitar',
    gender: 'femenino',
  },
  {
    word: 'mochila',
    article: 'la',
    translationRu: 'рюкзак',
    translationHy: 'պայուսակ',
    isException: false,
    icon: 'Briefcase',
    gender: 'femenino',
  },
  {
    word: 'música',
    article: 'la',
    translationRu: 'музыка',
    translationHy: 'երաժշտություն',
    isException: false,
    icon: 'Music2',
    gender: 'femenino',
  },
  {
    word: 'canción',
    article: 'la',
    translationRu: 'песня',
    translationHy: 'երգ',
    isException: false,
    icon: 'Radio',
    gender: 'femenino',
  },
  {
    word: 'escuela',
    article: 'la',
    translationRu: 'школа',
    translationHy: 'դպրոց',
    isException: false,
    icon: 'GraduationCap',
    gender: 'femenino',
  },
  // Exceptions Femenino
  {
    word: 'mano',
    article: 'la',
    translationRu: 'рука',
    translationHy: 'ձեռք',
    isException: true,
    icon: 'Hand',
    gender: 'femenino',
  },
  {
    word: 'foto',
    article: 'la',
    translationRu: 'фото',
    translationHy: 'լուսանկար',
    isException: true,
    icon: 'Camera',
    gender: 'femenino',
  },
  {
    word: 'moto',
    article: 'la',
    translationRu: 'мотоцикл',
    translationHy: 'մոտոցիկլ',
    isException: true,
    icon: 'Bike',
    gender: 'femenino',
  },
];

export const DJ_PRAISES: FeedbackMessage[] = [
  { es: '¡Muy bien!', ru: 'Отлично!', hy: 'Շատ լավ է։' },
  { es: '¡Excelente!', ru: 'Молодец!', hy: 'Գերազանց։' },
  { es: '¡Vamos!', ru: 'Погнали!', hy: 'Առա՛ջ։' },
  { es: '¡Buen ritmo!', ru: 'Классный ритм!', hy: 'Լավ ռիթմ է։' },
  { es: '¡Sigue así!', ru: 'Продолжай так же!', hy: 'Շարունակիր նույն ոգով։' },
];

export const UI_TEXTS = {
  ru: {
    appTitle: 'DJ ESPAÑOL',
    appSub: 'Музыкальный род испанских существительных',
    chooseLang: 'Выбери язык обучения:',
    startLesson: 'Начать урок 🎧',
    back: 'Назад',
    next: 'Далее',
    continue: 'Продолжить',
    ruleTitle: 'Правило DJ пульты 🎚️',
    ruleIntro: 'В испанском языке у существительных есть род. Как стороны винила, они бывают мужскими и женскими:',
    ruleMasculino: 'Мужской род — Masculino',
    ruleFemenino: 'Женский род — Femenino',
    ruleArticleM: 'Главный артикль: el',
    ruleArticleF: 'Главный артикль: la',
    ruleEndingO: 'Слова на -o чаще мужского рода:',
    ruleEndingA: 'Слова на -a чаще женского рода:',
    ruleExceptions: '⚡ Исключения (нужно просто запомнить их ритм!):',
    ruleFooter: 'Готов послушать и выучить эти слова? Погнали!',
    cardsTitle: 'Виниловые карточки слов',
    cardsSubtitle: 'Нажми на карту, чтобы послушать её музыкальный инструмент и перевод!',
    game1Title: 'Игра «El o La?»',
    game1Subtitle: 'Выбери правильный артикль для трека! Почувствуй ритм окончания.',
    game2Title: 'Игра «DJ Sort»',
    game2Subtitle: 'Перетащи или нажми на пластинку, чтобы отправить её в правильную колонку!',
    game3Title: 'Музыкальный Сэмплер',
    game3Subtitle: 'Твои правильные ответы разблокировали инструменты! Нажимай на пэды, чтобы создать свой трек.',
    game4Title: 'DJ Mix Challenge ⚡',
    game4Subtitle: 'Пройди супер-испытание из 10 вопросов! Каждый верный ответ добавит инструмент в твой DJ-микс.',
    correct: 'Правильно!',
    incorrect: 'Почти правильно!',
    explanationO: 'заканчивается на -o, чаще это мужской род (el).',
    explanationA: 'заканчивается на -a, чаще это женский род (la).',
    explanationExc: 'это слово-исключение! Запомни его род.',
    score: 'Очки',
    streak: 'Серия комбо',
    restart: 'Повторить урок 🔄',
    playAgain: 'Играть снова 🎧',
    switchLang: 'Сменить язык 🌎',
    congratsTitle: 'Рейтинг DJ микса:',
    rankBeginner: 'Начинающий DJ 🎧',
    rankAmateur: 'DJ ученик 🎵',
    rankSuper: 'Super DJ del español 👑',
    stars: 'Звёзды',
    perfect: 'Идеально! Настоящий мастер ритма!',
    helpCharacter: 'Совет от DJ:',
    dropHere: 'Перетащи сюда',
    colEl: 'Колонка EL',
    colLa: 'Колонка LA',
  },
  hy: {
    appTitle: 'DJ ESPAÑOL',
    appSub: 'Իսպաներեն գոյականների սեռերը երաժշտական ռիթմով',
    chooseLang: 'Ընտրիր ուսուցման լեզուն՝',
    startLesson: 'Սկսել դասը 🎧',
    back: 'Հետ',
    next: 'Առաջ',
    continue: 'Շարունակել',
    ruleTitle: 'DJ Վահանակի Կանոնը 🎚️',
    ruleIntro: 'Իսպաներենում գոյականներն ունեն սեռ: Ինչպես վինիլի երկու կողմերը, դրանք լինում են արական և իգական:',
    ruleMasculino: 'Արական սեռ — Masculino',
    ruleFemenino: 'Իգական սեռ — Femenino',
    ruleArticleM: 'Հիմնական հոդը՝ el',
    ruleArticleF: 'Հիմնական հոդը՝ la',
    ruleEndingO: '«-o» տառով վերջացող բառերը սովորաբար արական են՝',
    ruleEndingA: '«-a» տառով վերջացող բառերը սովորաբար իգական են՝',
    ruleExceptions: '⚡ Բացառություններ (պարզապես պետք է հիշել դրանց ռիթմը):',
    ruleFooter: 'Պատրա՞ստ ես լսել և սովորել այս բառերը: Գնացի՛նք։',
    cardsTitle: 'Վինիլային Բառաքարտեր',
    cardsSubtitle: 'Սեղմիր քարտի վրա՝ թարգմանությունը տեսնելու և երաժշտական գործիքը լսելու համար:',
    game1Title: 'Խաղ «El թե՞ La»',
    game1Subtitle: 'Ընտրիր ճիշտ հոդը տվյալ բառի համար: Զգա՛ վերջավորության ռիթմը։',
    game2Title: 'Խաղ «DJ Sort»',
    game2Subtitle: 'Տեղափոխիր կամ սեղմիր սկավառակը՝ այն ճիշտ բարձրախոսի մեջ դնելու համար:',
    game3Title: 'Երաժշտական Սեմփլեր',
    game3Subtitle: 'Քո ճիշտ պատասխանները բացել են նոր գործիքներ: Սեղմիր կոճակները քո սեփական թրեքը ստեղծելու համար:',
    game4Title: 'DJ Mix Challenge ⚡',
    game4Subtitle: 'Անցիր 10 հարցից բաղկացած գեր-փորձությունը: Ամեն ճիշտ պատասխան կավելացնի գործիք քո DJ-միքսին:',
    correct: 'Ճի՛շտ է։',
    incorrect: 'Գրեթե ճիշտ է։',
    explanationO: 'վերջանում է -o տառով, սովորաբար արական սեռ է (el)։',
    explanationA: 'վերջանում է -a տառով, սովորաբար իգական սեռ է (la)։',
    explanationExc: 'սա բացառություն է բառերի մեջ: Հիշիր դրա սեռը։',
    score: 'Միավորներ',
    streak: 'Կոմբո սերիա',
    restart: 'Կրկնել դասը 🔄',
    playAgain: 'Խաղալ նորից 🎧',
    switchLang: 'Փոխել լեզուն 🌎',
    congratsTitle: 'DJ միքսի վարկանիշը՝',
    rankBeginner: 'Սկսնակ DJ 🎧',
    rankAmateur: 'DJ աշակերտ 🎵',
    rankSuper: 'Super DJ del español 👑',
    stars: 'Աստղեր',
    perfect: 'Կատարյալ է: Դու ռիթմի իսկական վարպետ ես:',
    helpCharacter: 'DJ-ի խորհուրդը՝',
    dropHere: 'Տեղադրիր այստեղ',
    colEl: 'Բարձրախոս EL',
    colLa: 'Բարձրախոս LA',
  },
};

export function generateQuizQuestions(): QuizQuestion[] {
  // We can shuffle and construct a neat list of quiz questions based on our word bank!
  const questions: QuizQuestion[] = [];
  
  // Let's create a mix of multiple choice questions (article selector, translation selectors, error spots)
  const words = [...SPANISH_WORDS].sort(() => Math.random() - 0.5);

  words.forEach((w, index) => {
    const isArticleType = index % 2 === 0;
    if (isArticleType) {
      questions.push({
        id: `q-${index}`,
        type: 'select-article',
        wordObj: w,
        promptRu: `Выбери правильный артикль для слова: ${w.word}`,
        promptHy: `Ընտրիր ճիշտ հոդը հետևյալ բառի համար՝ ${w.word}`,
        options: ['el', 'la'],
        correctAnswer: w.article,
      });
    } else {
      // Choose translation
      const otherWords = SPANISH_WORDS.filter(item => item.word !== w.word);
      const wrong1 = otherWords[0];
      const wrong2 = otherWords[1];
      
      const optionsRu = [w.word, wrong1.word, wrong2.word].sort(() => Math.random() - 0.5);
      const optionsHy = [w.word, wrong1.word, wrong2.word].sort(() => Math.random() - 0.5);

      questions.push({
        id: `q-${index}`,
        type: 'match-translation',
        wordObj: w,
        promptRu: `Какое испанское слово означает: "${w.translationRu}"?`,
        promptHy: `Ո՞ր իսպաներեն բառն է նշանակում՝ "${w.translationHy}":`,
        options: optionsRu,
        correctAnswer: w.word,
      });
    }
  });

  return questions;
}
